import type { Product } from '@/lib/types';

export const products: Product[] = [
  {
    id: 'st-cam-001',
    name: 'Sentinel 4K AI Camera',
    description: 'Ultra-high-definition 4K security camera with AI-powered person and vehicle detection. Weatherproof and night vision capable.',
    price: 249.99,
    image: 'https://placehold.co/600x600',
    category: 'Cameras',
    specs: {
      Resolution: '4K Ultra HD',
      'Field of View': '120°',
      'Night Vision': 'Up to 100ft',
      'Power Source': 'PoE (Power over Ethernet)',
      Weatherproof: 'IP67 Rated',
    },
  },
  {
    id: 'st-lock-002',
    name: 'Aegis Smart Lock Pro',
    description: 'Keyless entry smart lock with fingerprint, keypad, and app access. Features auto-lock and activity logs.',
    price: 199.99,
    image: 'https://placehold.co/600x600',
    category: 'Access Control',
    specs: {
      'Unlock Methods': 'Fingerprint, Code, App, Key',
      'Battery Life': '12 months',
      'Material': 'Zinc Alloy',
      'Compatibility': 'iOS, Android, Alexa',
    },
  },
  {
    id: 'st-alarm-003',
    name: 'Guardian All-in-One Alarm',
    description: 'Comprehensive home security system with door/window sensors, motion detector, and a central hub with a built-in siren.',
    price: 399.00,
    image: 'https://placehold.co/600x600',
    category: 'Alarm Systems',
    specs: {
      'Kit Includes': 'Hub, 2x Door Sensors, 1x Motion Sensor',
      'Connectivity': 'Wi-Fi, Cellular Backup',
      'Siren Volume': '105 dB',
      'Monitoring': 'Optional Professional Monitoring',
    },
  },
  {
    id: 'st-dcam-004',
    name: 'Doorbell Vision+',
    description: 'Smart video doorbell with 2K resolution, two-way audio, and package detection. Never miss a visitor.',
    price: 179.50,
    image: 'https://placehold.co/600x600',
    category: 'Cameras',
    specs: {
      Resolution: '2K QHD',
      'Audio': 'Two-way with Noise Cancellation',
      'Power': 'Wired or Battery',
      Storage: 'Local & Cloud Options',
    },
  },
   {
    id: 'st-safe-005',
    name: 'Fortress Biometric Safe',
    description: 'A heavy-duty steel safe secured by a state-of-the-art biometric fingerprint scanner. Fireproof and waterproof for ultimate protection.',
    price: 499.99,
    image: 'https://placehold.co/600x600',
    category: 'Safes',
    specs: {
      'Material': '12-gauge solid steel',
      'Fire Rating': '1 hour at 1700°F',
      'Waterproof': '24 hours in 8ft of water',
      'Capacity': '1.23 cubic feet',
    },
  },
  {
    id: 'st-panel-006',
    name: 'Command Center Touchscreen',
    description: '7-inch touchscreen hub to control all your Sicher Tech devices. Arm/disarm, view cameras, and manage access from one place.',
    price: 299.00,
    image: 'https://placehold.co/600x600',
    category: 'Access Control',
    specs: {
      'Screen Size': '7 inches',
      'Resolution': '1024 x 600',
      'Connectivity': 'Wi-Fi, Z-Wave, Bluetooth',
      'Power': 'AC Power with Battery Backup',
    },
  },
  {
    id: 'st-sensor-007',
    name: 'Enviro-Sensor Suite',
    description: 'Monitor your environment with sensors for smoke, carbon monoxide, and water leaks. Get instant alerts on your phone.',
    price: 129.00,
    image: 'https://placehold.co/600x600',
    category: 'Sensors',
    specs: {
      'Sensors': 'Smoke, CO, Water Leak',
      'Connectivity': 'Z-Wave',
      'Battery Life': '5 years',
      'Compatibility': 'Sicher Tech Command Center',
    },
  },
  {
    id: 'st-solar-008',
    name: 'Solar Panel for Cameras',
    description: 'Keep your battery-powered cameras continuously charged with this efficient, weatherproof solar panel.',
    price: 59.99,
    image: 'https://placehold.co/600x600',
    category: 'Accessories',
    specs: {
      'Power Output': '5W',
      'Cable Length': '13ft (4m)',
      'Weatherproof': 'IP65',
      'Compatibility': 'Sentinel Battery Cam, Doorbell Vision+',
    },
  },
];
